:PROPERTIES:
:header-args:python: :session py-pudl-3910 :async :results output drawer :tangle
:END:

#+title: pudl-3910 EDA
#+author: Nilay Kumar
#+date: <2024-12-29 Sun>

* Introduction

** Objective
Zane Selvans' write-up for the GitHub issue is super detailed and has plenty of
references, so I'll simply link to the [[https://github.com/catalyst-cooperative/pudl/issues/3910][issue]] itself for an introduction. To
summarize: we wish to study any biases in the demand forecasts of regulated
utilities in the United States.

** Context
Utilities have historically overestimated load growth, and given that we are in
a fresh new hype cycle around large-scale data and artificial intelligence, it
is possible that utilities are using this hype as justification to build out
"emergency" infrastructure that includes new fossil fuel components.

** Dataset

We will be using publicly available US government data that has been cleaned and
made available through PUDL's pipeline. The data dictionary can be found [[https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html][here]].

** Library imports
#+begin_src python :results none
from datetime import datetime
import polars as pl
import matplotlib.pyplot as plt
#+end_src

*** TODO add links or write a script to pull the latest version of the data programmatically

* Load and clean data

** Demand forecasts
#+begin_src python
forecasts = pl.read_parquet("data/core_ferc714__yearly_planning_area_demand_forecast.parquet")
print(forecasts.describe())
#+end_src

#+RESULTS:
:results:
shape: (9, 7)
┌────────────┬─────────────────┬─────────────┬───────────────┬─────────────────┬─────────────────┬─────────────────┐
│ statistic  ┆ respondent_id_f ┆ report_year ┆ forecast_year ┆ summer_peak_dem ┆ winter_peak_dem ┆ net_demand_fore │
│ ---        ┆ erc714          ┆ ---         ┆ ---           ┆ and_forecast_mw ┆ and_forecast_mw ┆ cast_mwh        │
│ str        ┆ ---             ┆ f64         ┆ f64           ┆ ---             ┆ ---             ┆ ---             │
│            ┆ f64             ┆             ┆               ┆ f64             ┆ f64             ┆ f64             │
╞════════════╪═════════════════╪═════════════╪═══════════════╪═════════════════╪═════════════════╪═════════════════╡
│ count      ┆ 20603.0         ┆ 20603.0     ┆ 20603.0       ┆ 20603.0         ┆ 20603.0         ┆ 20603.0         │
│ null_count ┆ 0.0             ┆ 0.0         ┆ 0.0           ┆ 0.0             ┆ 0.0             ┆ 0.0             │
│ mean       ┆ 101.901082      ┆ 2013.441926 ┆ 2018.948114   ┆ 29333.082031    ┆ 6637.583496     ┆ 6.5436364e7     │
│ std        ┆ 54.626225       ┆ 5.276922    ┆ 6.034354      ┆ 974579.0625     ┆ 17195.330078    ┆ 3.87128512e8    │
│ min        ┆ 1.0             ┆ 2006.0      ┆ 2007.0        ┆ 0.0             ┆ 0.0             ┆ 0.0             │
│ 25%        ┆ 57.0            ┆ 2009.0      ┆ 2014.0        ┆ 668.0           ┆ 538.0           ┆ 1.529e6         │
│ 50%        ┆ 106.0           ┆ 2013.0      ┆ 2019.0        ┆ 1813.0          ┆ 1665.0          ┆ 6.083e6         │
│ 75%        ┆ 147.0           ┆ 2018.0      ┆ 2023.0        ┆ 5032.761719     ┆ 4497.0          ┆ 1.81146e7       │
│ max        ┆ 217.0           ┆ 2023.0      ┆ 2045.0        ┆ 4.8977424e7     ┆ 163069.0        ┆ 5.9453e9        │
└────────────┴─────────────────┴─────────────┴───────────────┴─────────────────┴─────────────────┴─────────────────┘
Cell Timer: 0:00:00
:end:

** Realized demand
The realized demand table ([[https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html#out-ferc714-hourly-planning-area-demand][documentation]]) contains hourly reported data.
#+begin_src python
real_demand = pl.read_parquet(
    "data/out_ferc714__hourly_planning_area_demand.parquet"
).drop(["respondent_id_ferc714_csv", "respondent_id_ferc714_xbrl"])
print(real_demand.describe())
#+end_src

#+RESULTS:
:results:
shape: (9, 6)
┌────────────┬───────────────────────┬─────────────────┬────────────────────────────┬──────────┬──────────────┐
│ statistic  ┆ respondent_id_ferc714 ┆ report_date     ┆ datetime_utc               ┆ timezone ┆ demand_mwh   │
│ ---        ┆ ---                   ┆ ---             ┆ ---                        ┆ ---      ┆ ---          │
│ str        ┆ f64                   ┆ str             ┆ str                        ┆ str      ┆ f64          │
╞════════════╪═══════════════════════╪═════════════════╪════════════════════════════╪══════════╪══════════════╡
│ count      ┆ 1.7968411e7           ┆ 17968411        ┆ 17968411                   ┆ 17968411 ┆ 1.7968411e7  │
│ null_count ┆ 0.0                   ┆ 0               ┆ 0                          ┆ 0        ┆ 0.0          │
│ mean       ┆ 101.855286            ┆ 2013-06-21      ┆ 2013-12-21 15:02:02.669000 ┆ null     ┆ 4349.916504  │
│            ┆                       ┆ 20:38:22.564000 ┆                            ┆          ┆              │
│ std        ┆ 54.59334              ┆ null            ┆ null                       ┆ null     ┆ 11578.292969 │
│ min        ┆ 1.0                   ┆ 2006-01-01      ┆ 2006-01-01 05:00:00        ┆ null     ┆ -614.0       │
│ 25%        ┆ 57.0                  ┆ 2009-01-01      ┆ 2009-03-27 09:00:00        ┆ null     ┆ 353.0        │
│ 50%        ┆ 106.0                 ┆ 2013-01-01      ┆ 2013-05-28 09:00:00        ┆ null     ┆ 1080.0       │
│ 75%        ┆ 146.0                 ┆ 2018-01-01      ┆ 2018-06-15 09:00:00        ┆ null     ┆ 2792.0       │
│ max        ┆ 217.0                 ┆ 2024-01-01      ┆ 2024-01-01 10:00:00        ┆ null     ┆ 158043.0     │
└────────────┴───────────────────────┴─────────────────┴────────────────────────────┴──────────┴──────────────┘
Cell Timer: 0:00:00
:end:

There are a number of respondents that have all 0s as their demand data. There
are also a number of negative values for demand (perhaps some form of credits).
#+begin_src python
print("IDs with all 0s for demand:")
print(real_demand.filter((pl.col("demand_mwh") == 0).all().over(pl.col("respondent_id_ferc714")))["respondent_id_ferc714"].unique().to_list())
print("Rows with negative demand:")
print(real_demand.filter(pl.col("demand_mwh") < 0).shape[0])
#+end_src

#+RESULTS:
:results:
IDs with all 0s for demand:
[31, 42, 47, 48, 97, 175, 180, 181]
Rows with negative demand:
105192
Cell Timer: 0:00:00
:end:

** Summarized demand
#+begin_src python
summ_demand = pl.read_parquet("data/out_ferc714__summarized_demand.parquet")
print(summ_demand.head())
#+end_src

#+RESULTS:
:results:
shape: (5, 16)
┌─────────────┬─────────────┬─────────────┬────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ report_date ┆ respondent_ ┆ demand_annu ┆ population ┆ … ┆ balancing_a ┆ balancing_a ┆ utility_id_ ┆ utility_nam │
│ ---         ┆ id_ferc714  ┆ al_mwh      ┆ ---        ┆   ┆ uthority_co ┆ uthority_na ┆ eia         ┆ e_eia       │
│ date        ┆ ---         ┆ ---         ┆ f32        ┆   ┆ de_eia      ┆ me_eia      ┆ ---         ┆ ---         │
│             ┆ i32         ┆ f32         ┆            ┆   ┆ ---         ┆ ---         ┆ i32         ┆ str         │
│             ┆             ┆             ┆            ┆   ┆ str         ┆ str         ┆             ┆             │
╞═════════════╪═════════════╪═════════════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2006-01-01  ┆ 1           ┆ 8.875388e6  ┆ 3.113764e6 ┆ … ┆ AEC         ┆ Alabama     ┆ null        ┆ null        │
│             ┆             ┆             ┆            ┆   ┆             ┆ Electric    ┆             ┆             │
│             ┆             ┆             ┆            ┆   ┆             ┆ Coop Inc    ┆             ┆             │
│ 2006-01-01  ┆ 2           ┆ 6.4585324e7 ┆ 3.938281e6 ┆ … ┆ null        ┆ null        ┆ 195         ┆ Alabama     │
│             ┆             ┆             ┆            ┆   ┆             ┆             ┆             ┆ Power Co    │
│ 2006-01-01  ┆ 3           ┆ 41192.21093 ┆ null       ┆ … ┆ YAD         ┆ Alcoa Power ┆ null        ┆ null        │
│             ┆             ┆ 8           ┆            ┆   ┆             ┆ Generating, ┆             ┆             │
│             ┆             ┆             ┆            ┆   ┆             ┆ Inc. -…     ┆             ┆             │
│ 2006-01-01  ┆ 4           ┆ 1.2844342e7 ┆ 1.00873e6  ┆ … ┆ null        ┆ Minnesota   ┆ null        ┆ null        │
│             ┆             ┆             ┆            ┆   ┆             ┆ Power, Inc  ┆             ┆             │
│ 2006-01-01  ┆ 5           ┆ 1.4564695e7 ┆ 2.47357e6  ┆ … ┆ null        ┆ null        ┆ 20856       ┆ Wisconsin   │
│             ┆             ┆             ┆            ┆   ┆             ┆             ┆             ┆ Power &     │
│             ┆             ┆             ┆            ┆   ┆             ┆             ┆             ┆ Light Co    │
└─────────────┴─────────────┴─────────────┴────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘
Cell Timer: 0:00:00
:end:

* Realized peak demand

We compute the yearly peak demand by taking a max over the =(respondent, year)=.
#+begin_src python
peak_yearly_demand = real_demand.with_columns(
    pl.col("demand_mwh")
    .max()
    .over(pl.col("respondent_id_ferc714"), pl.col("datetime_utc").dt.year())
    .alias("peak_demand_mw")
)
print(
    peak_yearly_demand.filter(
        pl.col("respondent_id_ferc714") == 127,
        pl.col("datetime_utc") >= datetime(2024, 1, 1),
    )
)
#+end_src

#+RESULTS:
:results:
shape: (8, 6)
┌───────────────────────┬─────────────┬─────────────────────┬─────────────────────┬────────────┬────────────────┐
│ respondent_id_ferc714 ┆ report_date ┆ datetime_utc        ┆ timezone            ┆ demand_mwh ┆ peak_demand_mw │
│ ---                   ┆ ---         ┆ ---                 ┆ ---                 ┆ ---        ┆ ---            │
│ i32                   ┆ date        ┆ datetime[ms]        ┆ cat                 ┆ f32        ┆ f32            │
╞═══════════════════════╪═════════════╪═════════════════════╪═════════════════════╪════════════╪════════════════╡
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 00:00:00 ┆ America/Los_Angeles ┆ 294.0      ┆ 300.0          │
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 01:00:00 ┆ America/Los_Angeles ┆ 300.0      ┆ 300.0          │
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 02:00:00 ┆ America/Los_Angeles ┆ 298.0      ┆ 300.0          │
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 03:00:00 ┆ America/Los_Angeles ┆ 291.0      ┆ 300.0          │
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 04:00:00 ┆ America/Los_Angeles ┆ 287.0      ┆ 300.0          │
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 05:00:00 ┆ America/Los_Angeles ┆ 280.0      ┆ 300.0          │
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 06:00:00 ┆ America/Los_Angeles ┆ 276.0      ┆ 300.0          │
│ 127                   ┆ 2023-01-01  ┆ 2024-01-01 07:00:00 ┆ America/Los_Angeles ┆ 270.0      ┆ 300.0          │
└───────────────────────┴─────────────┴─────────────────────┴─────────────────────┴────────────┴────────────────┘
Cell Timer: 0:00:00
:end:

* Reproducing the RMI plot

To analyze the difference between forecasted peak demand and realized peak
demand, we join the two relevant tables.
#+begin_src python
df = forecasts.with_columns(
    peak_demand_forecast_mw=pl.max_horizontal(
        "summer_peak_demand_forecast_mw", "winter_peak_demand_forecast_mw"
    )
).join(
    peak_yearly_demand.with_columns(real_year=pl.col("datetime_utc").dt.year())
    .select("respondent_id_ferc714", "real_year", "peak_demand_mw")
    .unique(),
    left_on=["respondent_id_ferc714", "forecast_year"],
    right_on=["respondent_id_ferc714", "real_year"],
    how="left",
)
df = df.with_columns(
    lookahead=pl.col("forecast_year") - pl.col("report_year"),
    delta=pl.col("peak_demand_forecast_mw") - pl.col("peak_demand_mw"),
).filter(pl.col("delta").is_not_null())
print(df.tail())
#+end_src

#+RESULTS:
:results:
shape: (5, 10)
┌───────────────┬─────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬───────────┬────────┐
│ respondent_id ┆ report_year ┆ forecast_yea ┆ summer_peak_ ┆ … ┆ peak_demand_ ┆ peak_demand_ ┆ lookahead ┆ delta  │
│ _ferc714      ┆ ---         ┆ r            ┆ demand_forec ┆   ┆ forecast_mw  ┆ mw           ┆ ---       ┆ ---    │
│ ---           ┆ i32         ┆ ---          ┆ ast_mw       ┆   ┆ ---          ┆ ---          ┆ i32       ┆ f32    │
│ i32           ┆             ┆ i32          ┆ ---          ┆   ┆ f32          ┆ f32          ┆           ┆        │
│               ┆             ┆              ┆ f32          ┆   ┆              ┆              ┆           ┆        │
╞═══════════════╪═════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪═══════════╪════════╡
│ 127           ┆ 2021        ┆ 2022         ┆ 314.0        ┆ … ┆ 412.0        ┆ 517.0        ┆ 1         ┆ -105.0 │
│ 127           ┆ 2021        ┆ 2023         ┆ 319.0        ┆ … ┆ 418.0        ┆ 442.0        ┆ 2         ┆ -24.0  │
│ 127           ┆ 2021        ┆ 2024         ┆ 324.0        ┆ … ┆ 425.0        ┆ 300.0        ┆ 3         ┆ 125.0  │
│ 127           ┆ 2022        ┆ 2023         ┆ 344.0        ┆ … ┆ 463.0        ┆ 442.0        ┆ 1         ┆ 21.0   │
│ 127           ┆ 2022        ┆ 2024         ┆ 364.0        ┆ … ┆ 495.0        ┆ 300.0        ┆ 2         ┆ 195.0  │
└───────────────┴─────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴───────────┴────────┘
Cell Timer: 0:00:00
:end:
