[project]
name = "pudl-3910"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "black[d]>=24.10.0",
    "jupyterlab-vim>=4.1.4",
    "jupyterlab>=4.3.0",
    "matplotlib>=3.9.2",
    "pandas[pyarrow]>=2.2.3",
    "polars>=1.12.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.21.0",
    "jupyter-black>=0.4.0",
]
